### ISSUE TITLE
Doesn't start using counter strike sharp v202

### ISSUE THREAD

**Issue by BoTo-sg** [Oylneechan/ConsoleChat#1]
13:32:37 [INFO] (cssharp:PluginContext) Loading plugin ConsoleChat
13:32:37 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/ConsoleChat/ConsoleChat.dll
System.NotSupportedException: Data type not supported:System.Char
   at CounterStrikeSharp.API.Modules.Memory.DataTypeExtensions.ToValidDataType(Type type) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DataType.cs:line 95
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionWithReturn`5..ctor(String signature) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionWithReturn.cs:line 82
   at ConsoleChat.ConsoleChat.Load(Boolean hotReload) in E:\Github\ConsoleChat\ConsoleChat.cs:line 17
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by Oylneechan** [comment]
if you get one from build folder, it's the old version.

just git clone this repository and dotnet build it.
